CREATE TABLE IF NOT EXISTS payment_table (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	title VARCHAR(100) NOT NULL,
	price REAL NOT NULL DEFAULT 0,
	quantity REAL NOT NULL DEFAULT 0,
	paydate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	amount REAL NOT NULL DEFAULT 0, 
	availability INTEGER DEFAULT 0
)